### ISSUE TITLE
Failed to connect to Mir: Failed to connect to server socket: No such file or directory

### ISSUE THREAD

**Issue by vincentlux** [lil-lab/drif#2]
Hi,
Thanks very much for releasing the code! I tried to set up the environment and run `python eval/evaluate.py corl_pvn_eval_pretrained_dev` on a remote server, however, the following error occurs:
```
DroneController Initialize
Wrote new AirSim settings to /home/xiaopen2/Documents/AirSim/settings.json
unsupported operand type(s) for *: 'AsyncIOLoop' and 'float'
Failed to connect to client on port 10000! Starting new AirSim...
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Failed to parse arguments: Cannot open display:
Error encountered during policy rollout!
unsupported operand type(s) for *: 'AsyncIOLoop' and 'float'
Traceback (most recent call last):
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/droneController.py", line 80, in startAirSim
    controller._start()
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/droneController.py", line 168, in _start
    self.client = MultirotorClient('127.0.0.1', self.port)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/airsimClientNew.py", line 442, in __init__
    super(MultirotorClient, self).__init__(ip, port)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/airsimClientNew.py", line 157, in __init__
    self.client = msgpackrpc.Client(msgpackrpc.Address(ip, port), timeout=10)
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/msgpackrpc/client.py", line 15, in __init__
    loop.attach_periodic_callback(self.step_timeout, 1000) # each 1s
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/msgpackrpc/loop.py", line 39, in attach_periodic_callback
    self._periodic_callback.start()
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/tornado/ioloop.py", line 887, in start
    self._schedule_next()
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/tornado/ioloop.py", line 915, in _schedule_next
    self._update_next(self.io_loop.time())
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/tornado/ioloop.py", line 922, in _update_next
    callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
TypeError: unsupported operand type(s) for *: 'AsyncIOLoop' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/rollout/roll_out.py", line 292, in roll_out_policy
    self.env = PomdpInterface(instance_id=self.instance_id)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/pomdp/pomdp_interface.py", line 33, in __init__
    self.drone = DroneController(instance=instance_id, flight_height=flight_height)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/droneController.py", line 122, in __init__
    startAirSim(self, instance, self.port)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/droneController.py", line 92, in startAirSim
    controller._start()
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/droneController.py", line 168, in _start
    self.client = MultirotorClient('127.0.0.1', self.port)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/airsimClientNew.py", line 442, in __init__
    super(MultirotorClient, self).__init__(ip, port)
  File "/home/xiaopen2/proj/semantic_mapping/nav/reproduce/drif/drones/airsim_interface/airsimClientNew.py", line 157, in __init__
    self.client = msgpackrpc.Client(msgpackrpc.Address(ip, port), timeout=10)
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/msgpackrpc/client.py", line 15, in __init__
    loop.attach_periodic_callback(self.step_timeout, 1000) # each 1s
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/msgpackrpc/loop.py", line 39, in attach_periodic_callback
    self._periodic_callback.start()
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/tornado/ioloop.py", line 887, in start
    self._schedule_next()
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/tornado/ioloop.py", line 915, in _schedule_next
    self._update_next(self.io_loop.time())
  File "/home/xiaopen2/software/miniconda3/envs/cuda9-py36/lib/python3.7/site-packages/tornado/ioloop.py", line 922, in _update_next
    callback_time_sec *= 1 + (self.jitter * (random.random() - 0.5))
TypeError: unsupported operand type(s) for *: 'AsyncIOLoop' and 'float'
```
I guess the error occurs on executing `gnome-terminal -x ~/proj/semantic_mapping/nav/reproduce/DroneSimulator/LinuxNoEditor/MyProject5.sh -WINDOWED -ResX=320 -ResY=240 -FPS=10 -WinX=0 -WinY=50 WorkerID 0 ApiServerPort 10000`, however, I tried a while and didn't see how to fix it. I ran the code on a remote server which I sshed into. Could you help me with it? Thank you very much!

**Comment by valtsblukis** [comment]
Hi! Thanks for reaching out! This error is most likely caused by conflicting versions of the Tornado library, which has changed it's API after version 6. The Microsoft AirSim version that our simulator is based on requires version 4.5.3. You can try to run:

`pip install tornado==4.5.3`

I recommend doing everything inside a conda or virtualenv environment, because this specific version might conflict with other requirements on your system. Let us know if this works, or if there are any further difficulties.

**Comment by vincentlux** [comment]
Hi! Thank you for your reply! I figured out that the issue comes from the xserver connection, and it works right now. Thank you for your help!
